services:
  bananavoice-api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bananavoice:${BANANAVOICE_VERSION:-latest}
    container_name: gothcorp-bananavoice-api
    restart: always
    env_file:
      - .env
    depends_on:
      bananavoice-db:
        condition: service_healthy
      bananavoice-redis:
        condition: service_healthy
      bananavoice-rmq:
        condition: service_healthy
    environment:
      BANANAVOICE_HOST: 0.0.0.0
      BANANAVOICE_DB_HOST: gothcorp-bananavoice-db
      BANANAVOICE_DB_PORT: 3306
      BANANAVOICE_DB_USER: bananavoice
      BANANAVOICE_DB_PASS: bananavoice
      BANANAVOICE_DB_BASE: bananavoice
      BANANAVOICE_RABBIT_HOST: gothcorp-bananavoice-rmq
      BANANAVOICE_REDIS_HOST: gothcorp-bananavoice-redis
    networks:
      - gothcorp

  bananavoice-worker:
    <<: *main_app
    container_name: gothcorp-bananavoice-worker
    labels: []
    command:
      - taskiq
      - worker
      - bananavoice.tkq:broker
    ports: []
    networks:
      - gothcorp

  bananavoice-db:
    image: mysql:8.4
    container_name: gothcorp-bananavoice-db
    hostname: gothcorp-bananavoice-db
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "bananavoice"
      MYSQL_USER: "bananavoice"
      MYSQL_PASSWORD: "bananavoice"
      MYSQL_DATABASE: "bananavoice"
      MYSQL_HOST: "0.0.0.0"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - --user=bananavoice
        - --password=bananavoice
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
      - "gothcorp-bananavoice-db-data:/var/lib/mysql"
    networks:
      - gothcorp

  bananavoice-migrator:
    image: bananavoice:${BANANAVOICE_VERSION:-latest}
    container_name: gothcorp-bananavoice-migrator
    restart: "no"
    command: alembic upgrade head
    environment:
      BANANAVOICE_DB_HOST: gothcorp-bananavoice-db
      BANANAVOICE_DB_PORT: 3306
      BANANAVOICE_DB_USER: bananavoice
      BANANAVOICE_DB_PASS: bananavoice
      BANANAVOICE_DB_BASE: bananavoice
    depends_on:
      bananavoice-db:
        condition: service_healthy
    networks:
      - gothcorp

  bananavoice-redis:
    image: bitnami/redis:6.2.5
    container_name: gothcorp-bananavoice-redis
    hostname: gothcorp-bananavoice-redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
    networks:
      - gothcorp

  bananavoice-rmq:
    image: rabbitmq:3.9.16-alpine
    container_name: gothcorp-bananavoice-rmq
    hostname: gothcorp-bananavoice-rmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50
    networks:
      - gothcorp

volumes:
  gothcorp-bananavoice-db-data:
    name: gothcorp-bananavoice-db-data

networks:
  gothcorp:
    external: true
    name: gothcorp
